# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
