# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mofied',
            new_name='modified',
        ),
    ]
